apiVersion: v1
kind: Service
metadata:
  name: campusxchange-api-svc
spec:
  type: NodePort
  selector:
    app: campusxchange-api-pod
  ports:
    - name: app-port-mapping
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: campusxchange-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: campusxchange-api-pod
  template:
    metadata:
      labels:
        app: campusxchange-api-pod
    spec:
      containers:
        - name: campusxchange-api
          image: campusxchange/campusxchange-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: postgres_host
                  name: campusxchange-config
            - name: MAIL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: mail_password
                  name: campusxchange-config
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: postgres_port
                  name: campusxchange-config
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: postgres_dbname
                  name: campusxchange-config
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: postgres_username
                  name: campusxchange-secrets
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgres_password
                  name: campusxchange-secrets